### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [o7-machinehum/Protectli-UPS-Firmware#1]
Hello!

I found this project from https://hackaday.com/2023/12/22/open-source-dc-ups-keeps-the-low-voltage-gear-going/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by o7-machinehum** [comment]
[Whoops!](https://github.com/o7-machinehum/Protectli-UPS-Firmware/commit/32d002966228f3d22da634c9d5dad635cde701be)

**Comment by vazhnov** [comment]
MIT license — amazing! Thank you!
