### ISSUE TITLE
PCBway & JLC Gerbers 

### ISSUE THREAD

**Issue by harrypm** [o7-machinehum/Protectli-UPS-Firmware#4]
It would be nice to have proper gerber/BOM file sets ready for direct fab use, as bare scamatics are sort of a dead on impact for people who want to get a physical thing to tinker with.

## Create Gerber Sets

- [ ] PCBway
- [ ] JLC

**Comment by o7-machinehum** [comment]
Board files and gerbers are not open source at this time.
